server:
  port: 12580
spring:
  datasource:
    password: Moxi123#
    url: jdbc:mysql://47.92.193.147:3306/outbound_call_platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  task:
    scheduling:
      pool:
        size: 5